theme: jekyll-theme-minimal
title: A collection of explorations
description: This page will host the notebooks created while exploring various topics involving computational physics, as part of my work during Summer 2021.  